[versions]
gradleplugin = "7.2.2"
detektplugin = "1.19.0"
kotlin = "1.7.10"
coroutines = "1.6.4"
#ext.kotlinVersion = '1.7.10'
#ext.composeVersion = '1.2.1'
#ext.composeCompilerVersion = '1.3.0'
#ext.accompanistVersion = '0.25.1'

[libraries]
mediafile = { module = "io.github.javernaut:mediafile", version = "1.0.3" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
material = { module = "com.google.android.material:material", version = "1.6.1" }
#gson = "com.google.code.gson:gson:2.9.0"

[bundles]
coroutines = ["coroutines-core", "coroutines-android"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektplugin" }