[versions]
gradleplugin = "8.3.1"
detektplugin = "1.23.5"
kotlin = "1.9.23"
coroutines = "1.8.0"
lifecycle = "2.7.0"
window = "1.2.0"
navigation = "2.7.7"

androidx-activity-compose = "1.8.2"
androidx-compose-bom = "2024.03.00"
androidx-compose-compiler = "1.5.11"

[libraries]
mediafile = "io.github.javernaut:mediafile:1.1.0"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

material = "com.google.android.material:material:1.11.0"

lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

window = { module = "androidx.window:window", version.ref = "window" }

liveevent = "com.github.hadilq.liveevent:liveevent:1.2.0"
palette = "androidx.palette:palette-ktx:1.0.0"
savedstate = "androidx.savedstate:savedstate:1.2.1"
viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"
browser = "androidx.browser:browser:1.8.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

[bundles]
coroutines = ["coroutines-core", "coroutines-android"]
lifecycle = ["lifecycle-viewmodel-ktx", "lifecycle-livedata-ktx", "lifecycle-viewmodel-savedstate"]
compose = ["androidx-compose-runtime", "androidx-compose-ui", "androidx-compose-foundation", "androidx-compose-foundation-layout", "androidx-compose-material", "androidx-compose-material-icons-extended", "androidx-compose-runtime-livedata", "androidx-compose-ui-tooling", "androidx-activity-compose", "androidx-compose-material3"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradleplugin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektplugin" }