[versions]
gradleplugin = "7.2.2"
detektplugin = "1.19.0"
kotlin = "1.7.10"
#ext.kotlinVersion = '1.7.10'
#ext.composeVersion = '1.2.1'
#ext.composeCompilerVersion = '1.3.0'
#ext.accompanistVersion = '0.25.1'

[libraries]
#room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
#room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
#room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
#room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#android-test-junit4 = { module = "androidx.test.ext:junit:1.1.3", version = "1.1.3" }
#gson = "com.google.code.gson:gson:2.9.0"

[bundles]
#room = ["room-ktx", "room-paging", "room-runtime"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektplugin" }