[versions]
gradleplugin = "8.1.3"
detektplugin = "1.23.1"
kotlin = "1.9.20"
coroutines = "1.7.3"
lifecycle = "2.6.2"
compose-animation = "1.5.4"
compose-compiler = "1.5.4"
compose-foundation = "1.5.4"
compose-material = "1.5.4"
compose-runtime = "1.5.4"
compose-ui = "1.5.4"

[libraries]
mediafile = "io.github.javernaut:mediafile:1.1.0-SNAPSHOT"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

material = "com.google.android.material:material:1.10.0"

lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

liveevent = "com.github.hadilq.liveevent:liveevent:1.2.0"
palette = "androidx.palette:palette-ktx:1.0.0"
savedstate = "androidx.savedstate:savedstate:1.2.1"
viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"
browser = "androidx.browser:browser:1.6.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose-foundation" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-runtime" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }

[bundles]
coroutines = ["coroutines-core", "coroutines-android"]
lifecycle = ["lifecycle-viewmodel-ktx", "lifecycle-livedata-ktx", "lifecycle-viewmodel-savedstate"]
compose = ["compose-runtime", "compose-ui", "compose-foundation", "compose-foundation-layout", "compose-material", "compose-material-icons-extended", "compose-runtime-livedata", "compose-ui-tooling", "androidx-activity-compose"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektplugin" }