complexity:
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreAnnotated: [ 'Parcelize', 'Composable' ]
  TooManyFunctions:
    active: true
    thresholdInFiles: 40
    thresholdInClasses: 30
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview', 'PreviewLightDark' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
