name: Integrity check
on: push
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Building the APK
        run: |
          export USERNAME=${{ github.actor }}
          export TOKEN=${{ secrets.GITHUB_TOKEN }}
          ./gradlew detekt buildCiDebug -Dorg.gradle.java.home=$JAVA_HOME_11_X64
