name: Release flow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: "Release AABs building and creating Github Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Overriding gradle.properties for CI
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Preparing secrets
        run: |
          mkdir signing
          
          echo signing.google.alias=${{ secrets.SIGNING_GOOGLE_ALIAS }} >> secrets.properties
          echo signing.google.password=${{ secrets.SIGNING_GOOGLE_PASSWORD }} >> secrets.properties
          echo signing.google.storePassword=${{ secrets.SIGNING_GOOGLE_STORE_PASSWORD }} >> secrets.properties
          
          echo "${{ secrets.SIGNING_GOOGLE_JKS }}" | base64 -d > signing/google.jks
          echo signing.google.storeFile=$(realpath signing/google.jks) >> secrets.properties
          
          echo signing.amazon.alias=${{ secrets.SIGNING_AMAZON_ALIAS }} >> secrets.properties
          echo signing.amazon.password=${{ secrets.SIGNING_AMAZON_PASSWORD }} >> secrets.properties
          echo signing.amazon.storePassword=${{ secrets.SIGNING_AMAZON_STORE_PASSWORD }} >> secrets.properties
          
          echo "${{ secrets.SIGNING_AMAZON_JKS }}" | base64 -d > signing/amazon.jks
          echo signing.amazon.storeFile=$(realpath signing/amazon.jks) >> secrets.properties
          
          echo signing.huawei.alias=${{ secrets.SIGNING_HUAWEI_ALIAS }} >> secrets.properties
          echo signing.huawei.password=${{ secrets.SIGNING_HUAWEI_PASSWORD }} >> secrets.properties
          echo signing.huawei.storePassword=${{ secrets.SIGNING_HUAWEI_STORE_PASSWORD }} >> secrets.properties
          
          echo "${{ secrets.SIGNING_HUAWEI_JKS }}" | base64 -d > signing/huawei.jks
          echo signing.huawei.storeFile=$(realpath signing/huawei.jks) >> secrets.properties

      - name: Run Detekt and build release variants for all markets
        run: ./gradlew detekt bundleRelease

      - name: Create Github Release and attach AABs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: |
            app/build/outputs/bundle/*/*.aab
